layers:
  - Iceland.yaml
# EPSG 3057
projection: >
  +proj=lcc +lat_1=64.25 +lat_2=65.75 +lat_0=65
  +lon_0=-19 +x_0=500000 +y_0=500000 +ellps=GRS80
  +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
resolution:
  max: 0.2 # m/px
  min: 1000 # m/px
bounds: [[-30,60],[-10,70]]
center: [-18,64]
